### ISSUE TITLE
Не получается запустить демку SynchClientServer-library

### ISSUE THREAD

**Issue by Diversus23** [Shanginre/SynchClientServer-library#1]
Добрый день.

Очень хочется использовать вашу ВК в своей работе, но я не могу запустить демку, которая идет в комплекте для тестирования.
Вот мои настройки:

![image](https://github.com/user-attachments/assets/5124acad-6afc-4d48-b720-17067009b9ad)

Пробовал без адреса удаленного сервера и с ним выдает одну и ту же ошибку:

![image](https://github.com/user-attachments/assets/bdc2ac51-5977-4fdb-b04b-0cf29803e247)

Очевидно, что проблема в установке настроек и нет понимания как это исправить.

Покажите какие параметры нужно внести, чтобы заработало?

Спасибо за вашу работу!

**Comment by Diversus23** [comment]
Уточнение. Выдается ошибка `Invalid error message : NativeLibrary.`

**Comment by Shanginre** [comment]
![image](https://github.com/user-attachments/assets/3574ce99-d4fe-4feb-b7d3-4bb59d6f7e30)
собственно в тесте ошибки ругается на параметры сервера. Попробуйте посмотреть под отладкой какие данные передаются в компоненту. Еще попробуйте поменять адрес и порт сервера, где собираетесь поднимать tcp сокет.

**Comment by Diversus23** [comment]
```json
{
"ip": "localhost",
"loggingRequired": true,
"logFileName": "c:\\www\\",
"memoryCleaningFrequency": 5000,
"serverTerminationSignal": "please stop it",
"ports": [
{
"portType": "TCP",
"portNumber": 9687,
"isLinkToRemoteServer": true,
"remoteIP": "localhost",
"delayReadingFromSocket": 100,
"delayMessageSending": 0,
"allowedTimeNoActivity": 30000
}
]
}
```

Вот такие настройки

**Comment by Shanginre** [comment]
"ip": "localhost",
"logFileName": "c:\\www\\",
"portNumber": 9687,
"remoteIP": "localhost",

попробуйте изменить эти настройки. А также убрать галочку "Связь с удаленным сервером", попробуйте просто поднять tcp сервер. А с взведенной галочкой вы наоборот становитесь клиентом

**Comment by Diversus23** [comment]
Ура! Спасибо!
