### ISSUE TITLE
При указании IP адреса компоненты сервиса "падает" предприятие.

### ISSUE THREAD

**Issue by alison-blake** [Shanginre/SynchClientServer-library#3]
Добрый день!
Поставил себе задачу обработать введение пользователем некорректного IP адреса компоненты. 

Провожу тестирование работы компоненты на файловой базе.
Компонента установлена на моем локальном компьютера, адрес которого 192.168.1.127. 
Использую его в качестве параметра "IPAдресКомпонентыСервера". 
Работает отлично без каких либо ошибок. 

- Но если я укажу хотя бы одну неверную цифру своего IP адреса, то при выполнить метод компоненты Listen() - падает ошибка (в исключение не заходит).  Аналогичным образом ведет себя предоставляемый тестовый стенд из cf-файл из репозитория.
- Ошибка логируется в журнал Windows. 
- Прикрепляю изображения:
![Параметры](https://github.com/user-attachments/assets/2f036702-c525-4d79-9e91-9da22e194ebb)

1) Параметры компоненты при попытке Listen()
2) Информация из журнала Windows:

![ЖурналWindows](https://github.com/user-attachments/assets/4f3a5c47-2cf5-4d59-a285-369f820fb56a)
![ОписаниеОшибки](https://github.com/user-attachments/assets/d0c9c91e-5886-48c1-9c1d-0084318f67b8)

**Comment by Shanginre** [comment]
Ошибка принята к исправлению
